#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

IMAGE_NAME="${IMAGE_NAME:-meva-yolo-demo}"
GUI_HOST="${GUI_HOST:-192.168.1.94}"
GUI_PORT="${GUI_PORT:-5000}"
SOURCE_ROOT="${SOURCE_ROOT:-/data/MEVA}"
CLIP_START_SECONDS="${CLIP_START_SECONDS:-0}"
CLIP_DURATION_SECONDS="${CLIP_DURATION_SECONDS:-10}"
SAMPLE_INTERVAL_SECONDS="${SAMPLE_INTERVAL_SECONDS:-3600}"
SAMPLE_START_RATIO="${SAMPLE_START_RATIO:-0.8}"
CONFIDENCE="${CONFIDENCE:-0.60}"
DETECTION_INTERVAL_SECONDS="${DETECTION_INTERVAL_SECONDS:-0.5}"
JPEG_QUALITY="${JPEG_QUALITY:-35}"
MAX_UDP_BYTES="${MAX_UDP_BYTES:-35000}"
INFERENCE_SIZE="${INFERENCE_SIZE:-640}"
STREAM_MAX_WIDTH="${STREAM_MAX_WIDTH:-640}"
STREAM_MAX_HEIGHT="${STREAM_MAX_HEIGHT:-360}"
STREAM_TARGET_FPS="${STREAM_TARGET_FPS:-0}"
ENABLE_FRAME_SKIP="${ENABLE_FRAME_SKIP:-true}"
MAX_FRAME_SKIP="${MAX_FRAME_SKIP:-8}"
INFERENCE_SOURCE_MAX_WIDTH="${INFERENCE_SOURCE_MAX_WIDTH:-0}"
INFERENCE_SOURCE_MAX_HEIGHT="${INFERENCE_SOURCE_MAX_HEIGHT:-0}"
ENABLE_ASYNC_ENCODING="${ENABLE_ASYNC_ENCODING:-true}"
ENABLE_TILE_INFERENCE="${ENABLE_TILE_INFERENCE:-false}"
HOST_MEVA_PATH="${HOST_MEVA_PATH:-$HOME/datashets/MEVA}"

BUILD_IMAGE=0
RUN_ENCODE_BENCHMARK=0

print_usage() {
  cat <<'EOF'
Usage:
  bash ./run_meva_yolo_demo.sh [--build]

Options:
  --build    Force rebuild the Docker image before running.
  --benchmark-encode
             Measure JPEG encode time for 1280x720 and 480x270 frames.

Environment overrides:
  GUI_HOST, GUI_PORT, SOURCE_ROOT, CLIP_START_SECONDS, CLIP_DURATION_SECONDS
  SAMPLE_INTERVAL_SECONDS, SAMPLE_START_RATIO, CONFIDENCE
  DETECTION_INTERVAL_SECONDS, JPEG_QUALITY, MAX_UDP_BYTES
  INFERENCE_SIZE, STREAM_MAX_WIDTH, STREAM_MAX_HEIGHT, STREAM_TARGET_FPS
  ENABLE_FRAME_SKIP, MAX_FRAME_SKIP
  INFERENCE_SOURCE_MAX_WIDTH, INFERENCE_SOURCE_MAX_HEIGHT
  ENABLE_ASYNC_ENCODING, ENABLE_TILE_INFERENCE
  HOST_MEVA_PATH, IMAGE_NAME
EOF
}

for arg in "$@"; do
  case "$arg" in
    --build)
      BUILD_IMAGE=1
      ;;
    --benchmark-encode)
      RUN_ENCODE_BENCHMARK=1
      ;;
    --help|-h)
      print_usage
      exit 0
      ;;
    *)
      echo "Unknown option: $arg" >&2
      print_usage
      exit 1
      ;;
  esac
done

if [[ ! -d "$HOST_MEVA_PATH" ]]; then
  echo "MEVA source directory not found: $HOST_MEVA_PATH" >&2
  exit 1
fi

if ! sudo docker image inspect "$IMAGE_NAME" >/dev/null 2>&1; then
  BUILD_IMAGE=1
fi

if [[ "$BUILD_IMAGE" -eq 1 ]]; then
  echo "Building Docker image: $IMAGE_NAME"
  sudo docker build -t "$IMAGE_NAME" "$SCRIPT_DIR"
fi

echo "Running Docker image: $IMAGE_NAME"
echo "GUI_HOST=$GUI_HOST GUI_PORT=$GUI_PORT"
echo "HOST_MEVA_PATH=$HOST_MEVA_PATH"
echo "DETECTION_INTERVAL_SECONDS=$DETECTION_INTERVAL_SECONDS"
echo "INFERENCE_SIZE=$INFERENCE_SIZE STREAM_MAX_WIDTH=$STREAM_MAX_WIDTH STREAM_MAX_HEIGHT=$STREAM_MAX_HEIGHT"
echo "STREAM_TARGET_FPS=$STREAM_TARGET_FPS ENABLE_FRAME_SKIP=$ENABLE_FRAME_SKIP MAX_FRAME_SKIP=$MAX_FRAME_SKIP"
echo "INFERENCE_SOURCE_MAX_WIDTH=$INFERENCE_SOURCE_MAX_WIDTH INFERENCE_SOURCE_MAX_HEIGHT=$INFERENCE_SOURCE_MAX_HEIGHT"
echo "ENABLE_ASYNC_ENCODING=$ENABLE_ASYNC_ENCODING"
echo "ENABLE_TILE_INFERENCE=$ENABLE_TILE_INFERENCE JPEG_QUALITY=$JPEG_QUALITY MAX_UDP_BYTES=$MAX_UDP_BYTES"

if [[ "$RUN_ENCODE_BENCHMARK" -eq 1 ]]; then
  BENCHMARK_HOST_OUTPUT_DIR="${BENCHMARK_HOST_OUTPUT_DIR:-$SCRIPT_DIR/benchmark-output}"
  BENCHMARK_OUTPUT_DIR="${BENCHMARK_OUTPUT_DIR:-/benchmark-output}"
  mkdir -p "$BENCHMARK_HOST_OUTPUT_DIR"

  sudo docker run --rm \
    --runtime nvidia \
    --network host \
    -e SOURCE_ROOT="$SOURCE_ROOT" \
    -e VIDEO_PATH="${VIDEO_PATH:-}" \
    -e JPEG_QUALITY="$JPEG_QUALITY" \
    -e BENCHMARK_FRAMES="${BENCHMARK_FRAMES:-180}" \
    -e WARMUP_FRAMES="${WARMUP_FRAMES:-20}" \
    -e BENCHMARK_SIZE_A="${BENCHMARK_SIZE_A:-1280x720}" \
    -e BENCHMARK_SIZE_B="${BENCHMARK_SIZE_B:-480x270}" \
    -e BENCHMARK_QUALITY_A="${BENCHMARK_QUALITY_A:-$JPEG_QUALITY}" \
    -e BENCHMARK_QUALITY_B="${BENCHMARK_QUALITY_B:-$JPEG_QUALITY}" \
    -e BENCHMARK_MAX_BYTES_A="${BENCHMARK_MAX_BYTES_A:-0}" \
    -e BENCHMARK_MAX_BYTES_B="${BENCHMARK_MAX_BYTES_B:-0}" \
    -e BENCHMARK_ADAPTIVE_A="${BENCHMARK_ADAPTIVE_A:-false}" \
    -e BENCHMARK_ADAPTIVE_B="${BENCHMARK_ADAPTIVE_B:-false}" \
    -e BENCHMARK_OUTPUT_DIR="$BENCHMARK_OUTPUT_DIR" \
    -v "$HOST_MEVA_PATH:$SOURCE_ROOT:ro" \
    -v "$BENCHMARK_HOST_OUTPUT_DIR:$BENCHMARK_OUTPUT_DIR" \
    --entrypoint python3 \
    "$IMAGE_NAME" \
    /app/benchmark_encode_time.py
  exit 0
fi

sudo docker run --rm \
  --runtime nvidia \
  --network host \
  -e GUI_HOST="$GUI_HOST" \
  -e GUI_PORT="$GUI_PORT" \
  -e SOURCE_ROOT="$SOURCE_ROOT" \
  -e CLIP_START_SECONDS="$CLIP_START_SECONDS" \
  -e CLIP_DURATION_SECONDS="$CLIP_DURATION_SECONDS" \
  -e SAMPLE_INTERVAL_SECONDS="$SAMPLE_INTERVAL_SECONDS" \
  -e SAMPLE_START_RATIO="$SAMPLE_START_RATIO" \
  -e CONFIDENCE="$CONFIDENCE" \
  -e DETECTION_INTERVAL_SECONDS="$DETECTION_INTERVAL_SECONDS" \
  -e INFERENCE_SIZE="$INFERENCE_SIZE" \
  -e JPEG_QUALITY="$JPEG_QUALITY" \
  -e MAX_UDP_BYTES="$MAX_UDP_BYTES" \
  -e STREAM_MAX_WIDTH="$STREAM_MAX_WIDTH" \
  -e STREAM_MAX_HEIGHT="$STREAM_MAX_HEIGHT" \
  -e STREAM_TARGET_FPS="$STREAM_TARGET_FPS" \
  -e ENABLE_FRAME_SKIP="$ENABLE_FRAME_SKIP" \
  -e MAX_FRAME_SKIP="$MAX_FRAME_SKIP" \
  -e INFERENCE_SOURCE_MAX_WIDTH="$INFERENCE_SOURCE_MAX_WIDTH" \
  -e INFERENCE_SOURCE_MAX_HEIGHT="$INFERENCE_SOURCE_MAX_HEIGHT" \
  -e ENABLE_ASYNC_ENCODING="$ENABLE_ASYNC_ENCODING" \
  -e ENABLE_TILE_INFERENCE="$ENABLE_TILE_INFERENCE" \
  -v "$HOST_MEVA_PATH:$SOURCE_ROOT:ro" \
  "$IMAGE_NAME"
