#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

IMAGE_NAME_INPUT="${IMAGE_NAME:-GUI_camera}"
IMAGE_NAME="${IMAGE_NAME_INPUT,,}"
CONTAINER_NAME="${CONTAINER_NAME:-gui_camera_node}"
BASE_IMAGE="${BASE_IMAGE:-ultralytics/ultralytics:latest-nvidia-arm64}"
MODEL_NAME="${MODEL_NAME:-yolo11s.pt}"

GUI_HOST="${GUI_HOST:-192.168.1.94}"
GUI_PORT="${GUI_PORT:-5000}"
CAMERA_SOURCE="${CAMERA_SOURCE:-/dev/video0}"
CAMERA_DEVICE="${CAMERA_DEVICE:-/dev/video0}"
CAMERA_BACKEND="${CAMERA_BACKEND:-any}"
CAMERA_WIDTH="${CAMERA_WIDTH:-1280}"
CAMERA_HEIGHT="${CAMERA_HEIGHT:-720}"
CAMERA_FPS="${CAMERA_FPS:-30}"
CAMERA_BUFFER_SIZE="${CAMERA_BUFFER_SIZE:-1}"
CAMERA_FOURCC="${CAMERA_FOURCC:-MJPG}"
MAX_READ_FAILURES="${MAX_READ_FAILURES:-30}"
REOPEN_DELAY_SECONDS="${REOPEN_DELAY_SECONDS:-1.0}"

CONFIDENCE="${CONFIDENCE:-0.60}"
DETECTION_INTERVAL_SECONDS="${DETECTION_INTERVAL_SECONDS:-0.5}"
INFERENCE_SIZE="${INFERENCE_SIZE:-640}"
JPEG_QUALITY="${JPEG_QUALITY:-45}"
MAX_UDP_BYTES="${MAX_UDP_BYTES:-55000}"
STREAM_MAX_WIDTH="${STREAM_MAX_WIDTH:-854}"
STREAM_MAX_HEIGHT="${STREAM_MAX_HEIGHT:-480}"
STREAM_TARGET_FPS="${STREAM_TARGET_FPS:-0}"
ENABLE_FRAME_SKIP="${ENABLE_FRAME_SKIP:-true}"
MAX_FRAME_SKIP="${MAX_FRAME_SKIP:-8}"
INFERENCE_SOURCE_MAX_WIDTH="${INFERENCE_SOURCE_MAX_WIDTH:-0}"
INFERENCE_SOURCE_MAX_HEIGHT="${INFERENCE_SOURCE_MAX_HEIGHT:-0}"
ENABLE_ASYNC_ENCODING="${ENABLE_ASYNC_ENCODING:-true}"
ENABLE_ASYNC_UDP_SEND="${ENABLE_ASYNC_UDP_SEND:-true}"
UDP_SEND_BUFFER_BYTES="${UDP_SEND_BUFFER_BYTES:-4194304}"
ENABLE_TILE_INFERENCE="${ENABLE_TILE_INFERENCE:-false}"
TILE_OVERLAP_RATIO="${TILE_OVERLAP_RATIO:-0.15}"
ALLOWED_CLASSES="${ALLOWED_CLASSES:-}"

BUILD_IMAGE=0

print_usage() {
  cat <<'EOF'
Usage:
  bash ./run_gui_camera_yolo_node.sh [--build]

This runner is fully standalone:
- no shared ROS2 workspace mount
- no shared topic dependency
- no minji-perception base requirement

Important environment overrides:
  IMAGE_NAME, CONTAINER_NAME, BASE_IMAGE, MODEL_NAME
  GUI_HOST, GUI_PORT
  CAMERA_SOURCE, CAMERA_DEVICE, CAMERA_BACKEND
  CAMERA_WIDTH, CAMERA_HEIGHT, CAMERA_FPS
  CAMERA_BUFFER_SIZE, CAMERA_FOURCC
  MAX_READ_FAILURES, REOPEN_DELAY_SECONDS
  CONFIDENCE, DETECTION_INTERVAL_SECONDS, INFERENCE_SIZE
  JPEG_QUALITY, MAX_UDP_BYTES
  STREAM_MAX_WIDTH, STREAM_MAX_HEIGHT, STREAM_TARGET_FPS
  ENABLE_FRAME_SKIP, MAX_FRAME_SKIP
  INFERENCE_SOURCE_MAX_WIDTH, INFERENCE_SOURCE_MAX_HEIGHT
  ENABLE_ASYNC_ENCODING, ENABLE_ASYNC_UDP_SEND, UDP_SEND_BUFFER_BYTES
  ENABLE_TILE_INFERENCE, TILE_OVERLAP_RATIO, ALLOWED_CLASSES
EOF
}

for arg in "$@"; do
  case "$arg" in
    --build)
      BUILD_IMAGE=1
      ;;
    --help|-h)
      print_usage
      exit 0
      ;;
    *)
      echo "Unknown option: $arg" >&2
      print_usage
      exit 1
      ;;
  esac
done

if ! sudo docker image inspect "$IMAGE_NAME" >/dev/null 2>&1; then
  BUILD_IMAGE=1
fi

if [[ "$BUILD_IMAGE" -eq 1 ]]; then
  echo "Building Docker image: $IMAGE_NAME"
  sudo docker build \
    --build-arg "BASE_IMAGE=$BASE_IMAGE" \
    --build-arg "MODEL_NAME=$MODEL_NAME" \
    -f "$SCRIPT_DIR/Dockerfile.gui_camera" \
    -t "$IMAGE_NAME" \
    "$SCRIPT_DIR"
fi

echo "Running standalone gui_camera YOLO container"
if [[ "$IMAGE_NAME_INPUT" != "$IMAGE_NAME" ]]; then
  echo "Docker image tags must be lowercase. Using IMAGE_NAME=$IMAGE_NAME (from $IMAGE_NAME_INPUT)"
fi
echo "IMAGE_NAME=$IMAGE_NAME"
echo "CONTAINER_NAME=$CONTAINER_NAME"
echo "BASE_IMAGE=$BASE_IMAGE"
echo "MODEL_NAME=$MODEL_NAME"
echo "GUI_HOST=$GUI_HOST GUI_PORT=$GUI_PORT"
echo "CAMERA_SOURCE=$CAMERA_SOURCE CAMERA_DEVICE=$CAMERA_DEVICE CAMERA_BACKEND=$CAMERA_BACKEND"
echo "CAMERA_WIDTH=$CAMERA_WIDTH CAMERA_HEIGHT=$CAMERA_HEIGHT CAMERA_FPS=$CAMERA_FPS"
echo "CAMERA_BUFFER_SIZE=$CAMERA_BUFFER_SIZE CAMERA_FOURCC=$CAMERA_FOURCC"
echo "MAX_READ_FAILURES=$MAX_READ_FAILURES REOPEN_DELAY_SECONDS=$REOPEN_DELAY_SECONDS"
echo "INFERENCE_SIZE=$INFERENCE_SIZE DETECTION_INTERVAL_SECONDS=$DETECTION_INTERVAL_SECONDS"
echo "STREAM_MAX_WIDTH=$STREAM_MAX_WIDTH STREAM_MAX_HEIGHT=$STREAM_MAX_HEIGHT"
echo "JPEG_QUALITY=$JPEG_QUALITY MAX_UDP_BYTES=$MAX_UDP_BYTES"

if sudo docker container inspect "$CONTAINER_NAME" >/dev/null 2>&1; then
  echo "Removing previous gui_camera container: $CONTAINER_NAME"
  sudo docker rm -f "$CONTAINER_NAME" >/dev/null
fi

docker_args=(
  --rm
  --name "$CONTAINER_NAME"
  --runtime nvidia
  --network host
  -e "GUI_HOST=$GUI_HOST"
  -e "GUI_PORT=$GUI_PORT"
  -e "CAMERA_SOURCE=$CAMERA_SOURCE"
  -e "CAMERA_BACKEND=$CAMERA_BACKEND"
  -e "CAMERA_WIDTH=$CAMERA_WIDTH"
  -e "CAMERA_HEIGHT=$CAMERA_HEIGHT"
  -e "CAMERA_FPS=$CAMERA_FPS"
  -e "CAMERA_BUFFER_SIZE=$CAMERA_BUFFER_SIZE"
  -e "CAMERA_FOURCC=$CAMERA_FOURCC"
  -e "MAX_READ_FAILURES=$MAX_READ_FAILURES"
  -e "REOPEN_DELAY_SECONDS=$REOPEN_DELAY_SECONDS"
  -e "CONFIDENCE=$CONFIDENCE"
  -e "DETECTION_INTERVAL_SECONDS=$DETECTION_INTERVAL_SECONDS"
  -e "INFERENCE_SIZE=$INFERENCE_SIZE"
  -e "JPEG_QUALITY=$JPEG_QUALITY"
  -e "MAX_UDP_BYTES=$MAX_UDP_BYTES"
  -e "STREAM_MAX_WIDTH=$STREAM_MAX_WIDTH"
  -e "STREAM_MAX_HEIGHT=$STREAM_MAX_HEIGHT"
  -e "STREAM_TARGET_FPS=$STREAM_TARGET_FPS"
  -e "ENABLE_FRAME_SKIP=$ENABLE_FRAME_SKIP"
  -e "MAX_FRAME_SKIP=$MAX_FRAME_SKIP"
  -e "INFERENCE_SOURCE_MAX_WIDTH=$INFERENCE_SOURCE_MAX_WIDTH"
  -e "INFERENCE_SOURCE_MAX_HEIGHT=$INFERENCE_SOURCE_MAX_HEIGHT"
  -e "ENABLE_ASYNC_ENCODING=$ENABLE_ASYNC_ENCODING"
  -e "ENABLE_ASYNC_UDP_SEND=$ENABLE_ASYNC_UDP_SEND"
  -e "UDP_SEND_BUFFER_BYTES=$UDP_SEND_BUFFER_BYTES"
  -e "ENABLE_TILE_INFERENCE=$ENABLE_TILE_INFERENCE"
  -e "TILE_OVERLAP_RATIO=$TILE_OVERLAP_RATIO"
  -e "ALLOWED_CLASSES=$ALLOWED_CLASSES"
)

if [[ -n "$CAMERA_DEVICE" && -e "$CAMERA_DEVICE" ]]; then
  docker_args+=(--device "$CAMERA_DEVICE:$CAMERA_DEVICE")
fi

if [[ "$CAMERA_BACKEND" == "gstreamer" ]] || [[ "$CAMERA_SOURCE" == *"nvarguscamerasrc"* ]]; then
  if [[ -S /tmp/argus_socket ]]; then
    docker_args+=(-v /tmp/argus_socket:/tmp/argus_socket)
  fi
fi

sudo docker run "${docker_args[@]}" "$IMAGE_NAME" python3 /app/gui_camera_yolo_node.py
