#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

IMAGE_NAME_INPUT="${IMAGE_NAME:-GUI_camera}"
IMAGE_NAME="${IMAGE_NAME_INPUT,,}"
BASE_IMAGE="${BASE_IMAGE:-minji-perception}"
WORKSPACE_DIR="${WORKSPACE_DIR:-$HOME/minji/ros2_ws}"
ROS_SETUP="${ROS_SETUP:-/opt/ros/jazzy/setup.bash}"
WORKSPACE_SETUP="${WORKSPACE_SETUP:-/ros2_ws/install/setup.bash}"

GUI_HOST="${GUI_HOST:-192.168.1.94}"
GUI_PORT="${GUI_PORT:-5000}"

INPUT_IMAGE_TOPIC="${INPUT_IMAGE_TOPIC:-/video/eo/preprocessed}"
SYNCED_IMAGE_TOPIC="${SYNCED_IMAGE_TOPIC:-/yolo/eo/image_raw}"
DETECTION_TOPIC="${DETECTION_TOPIC:-/detections/eo}"
DRIVER_DETECTION_TOPIC="${DRIVER_DETECTION_TOPIC:-/driver/eo/detection}"
STATUS_TOPIC="${STATUS_TOPIC:-/yolo/eo/status}"
OUTPUT_FRAME_ID="${OUTPUT_FRAME_ID:-gui_camera_eo}"

MODEL_PATH="${MODEL_PATH:-/ros2_ws/src/yolo_detector_pkg/model/best.onnx}"
MODEL_INPUT_SIZE="${MODEL_INPUT_SIZE:-640}"
CONFIDENCE="${CONFIDENCE:-0.60}"
DETECTION_INTERVAL_SECONDS="${DETECTION_INTERVAL_SECONDS:-0.20}"
STREAM_MAX_WIDTH="${STREAM_MAX_WIDTH:-854}"
STREAM_MAX_HEIGHT="${STREAM_MAX_HEIGHT:-480}"
JPEG_QUALITY="${JPEG_QUALITY:-45}"
MAX_UDP_BYTES="${MAX_UDP_BYTES:-55000}"
UDP_SEND_BUFFER_BYTES="${UDP_SEND_BUFFER_BYTES:-4194304}"
STATUS_INTERVAL_SECONDS="${STATUS_INTERVAL_SECONDS:-1.0}"
ENABLE_GUI_FORWARD="${ENABLE_GUI_FORWARD:-true}"
ENABLE_TILE_INFERENCE="${ENABLE_TILE_INFERENCE:-false}"
TILE_OVERLAP_RATIO="${TILE_OVERLAP_RATIO:-0.15}"
ALLOWED_CLASSES="${ALLOWED_CLASSES:-}"

BUILD_IMAGE=0

print_usage() {
  cat <<'EOF'
Usage:
  bash ./run_gui_camera_yolo_node.sh [--build]

Options:
  --build    Force rebuild of the GUI_camera image.

Important environment overrides:
  IMAGE_NAME, BASE_IMAGE
  WORKSPACE_DIR, ROS_SETUP, WORKSPACE_SETUP
  GUI_HOST, GUI_PORT
  INPUT_IMAGE_TOPIC, SYNCED_IMAGE_TOPIC, DETECTION_TOPIC
  DRIVER_DETECTION_TOPIC, STATUS_TOPIC, OUTPUT_FRAME_ID
  MODEL_PATH, MODEL_INPUT_SIZE, CONFIDENCE, DETECTION_INTERVAL_SECONDS
  STREAM_MAX_WIDTH, STREAM_MAX_HEIGHT, JPEG_QUALITY, MAX_UDP_BYTES
  UDP_SEND_BUFFER_BYTES, STATUS_INTERVAL_SECONDS
  ENABLE_GUI_FORWARD, ENABLE_TILE_INFERENCE, TILE_OVERLAP_RATIO, ALLOWED_CLASSES
EOF
}

for arg in "$@"; do
  case "$arg" in
    --build)
      BUILD_IMAGE=1
      ;;
    --help|-h)
      print_usage
      exit 0
      ;;
    *)
      echo "Unknown option: $arg" >&2
      print_usage
      exit 1
      ;;
  esac
done

if [[ ! -d "$WORKSPACE_DIR" ]]; then
  echo "Workspace directory not found: $WORKSPACE_DIR" >&2
  exit 1
fi

if ! sudo docker image inspect "$IMAGE_NAME" >/dev/null 2>&1; then
  BUILD_IMAGE=1
fi

if [[ "$BUILD_IMAGE" -eq 1 ]]; then
  echo "Building Docker image: $IMAGE_NAME"
  sudo docker build \
    --build-arg "BASE_IMAGE=$BASE_IMAGE" \
    -f "$SCRIPT_DIR/Dockerfile.gui_camera" \
    -t "$IMAGE_NAME" \
    "$SCRIPT_DIR"
fi

echo "Running GUI_camera ROS2 YOLO node"
if [[ "$IMAGE_NAME_INPUT" != "$IMAGE_NAME" ]]; then
  echo "Docker image tags must be lowercase. Using IMAGE_NAME=$IMAGE_NAME (from $IMAGE_NAME_INPUT)"
fi
echo "IMAGE_NAME=$IMAGE_NAME BASE_IMAGE=$BASE_IMAGE"
echo "WORKSPACE_DIR=$WORKSPACE_DIR"
echo "GUI_HOST=$GUI_HOST GUI_PORT=$GUI_PORT"
echo "INPUT_IMAGE_TOPIC=$INPUT_IMAGE_TOPIC"
echo "SYNCED_IMAGE_TOPIC=$SYNCED_IMAGE_TOPIC"
echo "DETECTION_TOPIC=$DETECTION_TOPIC"
echo "DRIVER_DETECTION_TOPIC=$DRIVER_DETECTION_TOPIC"
echo "STATUS_TOPIC=$STATUS_TOPIC"
echo "MODEL_PATH=$MODEL_PATH"

sudo docker run --rm \
  --runtime nvidia \
  --network host \
  -v "$WORKSPACE_DIR:/ros2_ws" \
  -e "ROS_SETUP=$ROS_SETUP" \
  -e "WORKSPACE_SETUP=$WORKSPACE_SETUP" \
  -e "GUI_HOST=$GUI_HOST" \
  -e "GUI_PORT=$GUI_PORT" \
  -e "INPUT_IMAGE_TOPIC=$INPUT_IMAGE_TOPIC" \
  -e "SYNCED_IMAGE_TOPIC=$SYNCED_IMAGE_TOPIC" \
  -e "DETECTION_TOPIC=$DETECTION_TOPIC" \
  -e "DRIVER_DETECTION_TOPIC=$DRIVER_DETECTION_TOPIC" \
  -e "STATUS_TOPIC=$STATUS_TOPIC" \
  -e "OUTPUT_FRAME_ID=$OUTPUT_FRAME_ID" \
  -e "MODEL_PATH=$MODEL_PATH" \
  -e "MODEL_INPUT_SIZE=$MODEL_INPUT_SIZE" \
  -e "CONFIDENCE=$CONFIDENCE" \
  -e "DETECTION_INTERVAL_SECONDS=$DETECTION_INTERVAL_SECONDS" \
  -e "STREAM_MAX_WIDTH=$STREAM_MAX_WIDTH" \
  -e "STREAM_MAX_HEIGHT=$STREAM_MAX_HEIGHT" \
  -e "JPEG_QUALITY=$JPEG_QUALITY" \
  -e "MAX_UDP_BYTES=$MAX_UDP_BYTES" \
  -e "UDP_SEND_BUFFER_BYTES=$UDP_SEND_BUFFER_BYTES" \
  -e "STATUS_INTERVAL_SECONDS=$STATUS_INTERVAL_SECONDS" \
  -e "ENABLE_GUI_FORWARD=$ENABLE_GUI_FORWARD" \
  -e "ENABLE_TILE_INFERENCE=$ENABLE_TILE_INFERENCE" \
  -e "TILE_OVERLAP_RATIO=$TILE_OVERLAP_RATIO" \
  -e "ALLOWED_CLASSES=$ALLOWED_CLASSES" \
  "$IMAGE_NAME" \
  bash -lc "source \"$ROS_SETUP\" && source \"$WORKSPACE_SETUP\" && python3 /app/gui_camera_yolo_node.py"
