@echo off
setlocal

if "%JETSON_HOST%"=="" set JETSON_HOST=192.168.1.50
if "%JETSON_PORT%"=="" set JETSON_PORT=5600
if "%CAMERA_INDEX%"=="" set CAMERA_INDEX=0
if "%FRAME_WIDTH%"=="" set FRAME_WIDTH=1280
if "%FRAME_HEIGHT%"=="" set FRAME_HEIGHT=720
if "%TARGET_FPS%"=="" set TARGET_FPS=10
if "%JPEG_QUALITY%"=="" set JPEG_QUALITY=70
if "%MAX_UDP_BYTES%"=="" set MAX_UDP_BYTES=60000
if "%SHOW_PREVIEW%"=="" set SHOW_PREVIEW=true

echo JETSON_HOST=%JETSON_HOST%
echo JETSON_PORT=%JETSON_PORT%
echo CAMERA_INDEX=%CAMERA_INDEX%
echo FRAME_WIDTH=%FRAME_WIDTH%
echo FRAME_HEIGHT=%FRAME_HEIGHT%
echo TARGET_FPS=%TARGET_FPS%
echo JPEG_QUALITY=%JPEG_QUALITY%
echo MAX_UDP_BYTES=%MAX_UDP_BYTES%
echo SHOW_PREVIEW=%SHOW_PREVIEW%

python webcam_udp_sender.py

endlocal
