#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

IMAGE_NAME_INPUT="${IMAGE_NAME:-GUI_camera_bridge}"
IMAGE_NAME="${IMAGE_NAME_INPUT,,}"
CONTAINER_NAME="${CONTAINER_NAME:-gui_camera_bridge}"
BASE_IMAGE="${BASE_IMAGE:-ros:jazzy-ros-base}"
WORKSPACE_DIR="${WORKSPACE_DIR:-/home/lig/gui_camera_ws}"
WORKSPACE_SETUP="${WORKSPACE_SETUP:-/ros2_ws/install/local_setup.bash}"
WORKSPACE_MOUNT_MODE="${WORKSPACE_MOUNT_MODE:-ro}"

GUI_HOST="${GUI_HOST:-192.168.1.94}"
EO_GUI_PORT="${EO_GUI_PORT:-5000}"
IR_GUI_PORT="${IR_GUI_PORT:-5001}"
EO_IMAGE_TOPIC="${EO_IMAGE_TOPIC:-/video/eo/preprocessed}"
IR_IMAGE_TOPIC="${IR_IMAGE_TOPIC:-/video/ir/preprocessed}"
EO_DETECTION_TOPIC="${EO_DETECTION_TOPIC:-/detections/eo}"
IR_DETECTION_TOPIC="${IR_DETECTION_TOPIC:-/detections/ir}"
STREAM_WIDTH="${STREAM_WIDTH:-640}"
STREAM_HEIGHT="${STREAM_HEIGHT:-360}"
JPEG_QUALITY="${JPEG_QUALITY:-35}"
UDP_SEND_BUFFER_BYTES="${UDP_SEND_BUFFER_BYTES:-4194304}"
SEND_STATUS_WITH_IMAGE="${SEND_STATUS_WITH_IMAGE:-true}"
JETSON_RECORDING_DIR="${JETSON_RECORDING_DIR:-/home/lig/Desktop/video}"
RECORDING_DIR="${RECORDING_DIR:-/recordings}"
RECORDING_ENABLED="${RECORDING_ENABLED:-true}"
RECORDING_SEGMENT_SECONDS="${RECORDING_SEGMENT_SECONDS:-30}"
RECORDING_FPS="${RECORDING_FPS:-15}"
RECORDING_HTTP_ENABLED="${RECORDING_HTTP_ENABLED:-true}"
RECORDING_HTTP_PORT="${RECORDING_HTTP_PORT:-8090}"
ROS_DOMAIN_ID_VALUE="${ROS_DOMAIN_ID:-}"
RMW_IMPLEMENTATION_VALUE="${RMW_IMPLEMENTATION:-}"

BUILD_IMAGE=0

print_usage() {
  cat <<'EOF'
Usage:
  bash ./run_camera_udp_bridge.sh [--build]

This runner uses a dedicated Docker image and does not depend on minji containers.

Important environment overrides:
  IMAGE_NAME, CONTAINER_NAME, BASE_IMAGE
  WORKSPACE_DIR, WORKSPACE_SETUP, WORKSPACE_MOUNT_MODE
  GUI_HOST, EO_GUI_PORT, IR_GUI_PORT
  EO_IMAGE_TOPIC, IR_IMAGE_TOPIC
  EO_DETECTION_TOPIC, IR_DETECTION_TOPIC
  STREAM_WIDTH, STREAM_HEIGHT, JPEG_QUALITY
  UDP_SEND_BUFFER_BYTES, SEND_STATUS_WITH_IMAGE
  JETSON_RECORDING_DIR, RECORDING_ENABLED, RECORDING_SEGMENT_SECONDS
  RECORDING_FPS, RECORDING_HTTP_ENABLED, RECORDING_HTTP_PORT
  ROS_DOMAIN_ID, RMW_IMPLEMENTATION
EOF
}

for arg in "$@"; do
  case "$arg" in
    --build)
      BUILD_IMAGE=1
      ;;
    --help|-h)
      print_usage
      exit 0
      ;;
    *)
      echo "Unknown option: $arg" >&2
      print_usage
      exit 1
      ;;
  esac
done

if ! sudo docker image inspect "$IMAGE_NAME" >/dev/null 2>&1; then
  BUILD_IMAGE=1
fi

if [[ "$BUILD_IMAGE" -eq 1 ]]; then
  echo "Building Docker image: $IMAGE_NAME"
  sudo docker build \
    --build-arg "BASE_IMAGE=$BASE_IMAGE" \
    -f "$SCRIPT_DIR/Dockerfile" \
    -t "$IMAGE_NAME" \
    "$SCRIPT_DIR"
fi

echo "Running camera UDP bridge container"
if [[ "$IMAGE_NAME_INPUT" != "$IMAGE_NAME" ]]; then
  echo "Docker image tags must be lowercase. Using IMAGE_NAME=$IMAGE_NAME (from $IMAGE_NAME_INPUT)"
fi
echo "IMAGE_NAME=$IMAGE_NAME"
echo "CONTAINER_NAME=$CONTAINER_NAME"
echo "BASE_IMAGE=$BASE_IMAGE"
echo "WORKSPACE_DIR=$WORKSPACE_DIR"
echo "WORKSPACE_SETUP=$WORKSPACE_SETUP"
echo "GUI_HOST=$GUI_HOST"
echo "EO_IMAGE_TOPIC=$EO_IMAGE_TOPIC EO_GUI_PORT=$EO_GUI_PORT"
echo "IR_IMAGE_TOPIC=$IR_IMAGE_TOPIC IR_GUI_PORT=$IR_GUI_PORT"
echo "EO_DETECTION_TOPIC=$EO_DETECTION_TOPIC"
echo "IR_DETECTION_TOPIC=$IR_DETECTION_TOPIC"
echo "JETSON_RECORDING_DIR=$JETSON_RECORDING_DIR"
echo "RECORDING_DIR=$RECORDING_DIR"
echo "RECORDING_SEGMENT_SECONDS=$RECORDING_SEGMENT_SECONDS"
echo "RECORDING_HTTP_PORT=$RECORDING_HTTP_PORT"
if [[ -n "$ROS_DOMAIN_ID_VALUE" ]]; then
  echo "ROS_DOMAIN_ID=$ROS_DOMAIN_ID_VALUE"
fi
if [[ -n "$RMW_IMPLEMENTATION_VALUE" ]]; then
  echo "RMW_IMPLEMENTATION=$RMW_IMPLEMENTATION_VALUE"
fi

if sudo docker container inspect "$CONTAINER_NAME" >/dev/null 2>&1; then
  echo "Removing previous container: $CONTAINER_NAME"
  sudo docker rm -f "$CONTAINER_NAME" >/dev/null
fi

mkdir -p "$JETSON_RECORDING_DIR"

docker_args=(
  run --rm
  --name "$CONTAINER_NAME"
  --network host
  --ipc host
  -e "GUI_HOST=$GUI_HOST"
  -e "EO_GUI_PORT=$EO_GUI_PORT"
  -e "IR_GUI_PORT=$IR_GUI_PORT"
  -e "EO_IMAGE_TOPIC=$EO_IMAGE_TOPIC"
  -e "IR_IMAGE_TOPIC=$IR_IMAGE_TOPIC"
  -e "EO_DETECTION_TOPIC=$EO_DETECTION_TOPIC"
  -e "IR_DETECTION_TOPIC=$IR_DETECTION_TOPIC"
  -e "STREAM_WIDTH=$STREAM_WIDTH"
  -e "STREAM_HEIGHT=$STREAM_HEIGHT"
  -e "JPEG_QUALITY=$JPEG_QUALITY"
  -e "UDP_SEND_BUFFER_BYTES=$UDP_SEND_BUFFER_BYTES"
  -e "SEND_STATUS_WITH_IMAGE=$SEND_STATUS_WITH_IMAGE"
  -e "RECORDING_DIR=$RECORDING_DIR"
  -e "RECORDING_ENABLED=$RECORDING_ENABLED"
  -e "RECORDING_SEGMENT_SECONDS=$RECORDING_SEGMENT_SECONDS"
  -e "RECORDING_FPS=$RECORDING_FPS"
  -e "RECORDING_HTTP_ENABLED=$RECORDING_HTTP_ENABLED"
  -e "RECORDING_HTTP_PORT=$RECORDING_HTTP_PORT"
  -e "WORKSPACE_SETUP=$WORKSPACE_SETUP"
  -v "$WORKSPACE_DIR:/ros2_ws:$WORKSPACE_MOUNT_MODE"
  -v "$JETSON_RECORDING_DIR:$RECORDING_DIR:rw"
)

if [[ -n "$ROS_DOMAIN_ID_VALUE" ]]; then
  docker_args+=(-e "ROS_DOMAIN_ID=$ROS_DOMAIN_ID_VALUE")
fi

if [[ -n "$RMW_IMPLEMENTATION_VALUE" ]]; then
  docker_args+=(-e "RMW_IMPLEMENTATION=$RMW_IMPLEMENTATION_VALUE")
fi

sudo docker "${docker_args[@]}" "$IMAGE_NAME"
